---
apiVersion: v1
kind: Namespace
metadata:
  name: gpfs-kernel-module
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kmm-ci-dockerfile
  namespace: gpfs-kernel-module
data:
  dockerfile: |
      ARG IBM_SCALE=quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-core-init@sha256:fde69d67fddd2e4e0b7d7d85387a221359daf332d135c9b9f239fb31b9b82fe0
      ARG DTK_AUTO=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:01e0e07cc6c41638f8e9022fb9aa36a7984efcde2166d8158fb59a6c9f7dbbdf
      ARG KERNEL_FULL_VERSION
      FROM ${IBM_SCALE} as src_image
      FROM ${DTK_AUTO} as builder
      COPY --from=src_image /usr/lpp/mmfs /usr/lpp/mmfs
      RUN /usr/lpp/mmfs/bin/mmbuildgpl
      FROM registry.redhat.io/ubi9/ubi-minimal
      ARG KERNEL_FULL_VERSION
      RUN mkdir -p /opt/lib/modules/${KERNEL_FULL_VERSION}
      COPY --from=builder /lib/modules/${KERNEL_FULL_VERSION}/extra/*.ko /opt/lib/modules/${KERNEL_FULL_VERSION}/
      RUN microdnf install kmod -y && microdnf clean all
      RUN depmod -b /opt
---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: example-module
  namespace: gpfs-kernel-module
spec:
  moduleLoader:
    serviceAccountName: simple-kmod-driver-container
    container:
      modprobe:
        moduleName: mmfslinux
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: "image-registry.openshift-image-registry.svc:5000/gpfs-kernel-module/gpfs_compat_kmod:${KERNEL_FULL_VERSION}"
          build:
            dockerfileConfigMap:
              name: kmm-ci-dockerfile
          sign:
            keySecret:
              name: my-signing-key
            certSecret:
              name: my-signing-key-pub
            filesToSign:
              - /opt/lib/modules/${KERNEL_FULL_VERSION}/mmfslinux.ko
  selector: # top-level selector
    kubernetes.io/arch: amd64
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-kmod-driver-container
  namespace: gpfs-kernel-module
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-kmod-driver-container
  namespace: gpfs-kernel-module
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-kmod-driver-container
  namespace: gpfs-kernel-module

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-kmod-driver-container
subjects:
  - kind: ServiceAccount
    name: simple-kmod-driver-container
# userNames:
#   - system:serviceaccount:simple-kmod-demo:simple-kmod-driver-container
