---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-scale-operator-controller-manager
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-kmod-driver-container
  namespace: openshift-operators
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-kmod-driver-container
  namespace: openshift-operators

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-kmod-driver-container
subjects:
  - kind: ServiceAccount
    name: storage-scale-operator-controller-manager
# userNames:
#   - system:serviceaccount:simple-kmod-demo:simple-kmod-driver-container
